### ISSUE TITLE
Subproject meetings

### ISSUE THREAD

**Issue by rartych** [camaraproject/RegionUserCount#1]
**Problem description**
Are virtual meetings planned for this subproject?

**Additional context**
I would like to join from CET timezone.

**Comment by chinaunicomyangfan** [comment]
> **Problem description** Are virtual meetings planned for this subproject?
> 
> **Additional context** I would like to join from CET timezone.

Thank you for your support. The meeting is planned and we will update it to the homepage once the meeting time is confirmed

**Comment by chinaunicomyangfan** [comment]
> **Problem description** Are virtual meetings planned for this subproject?
> 
> **Additional context** I would like to join from CET timezone.

We have tentatively set the meeting time and schedule. If adjustments are needed, the specific time can be discussed at our first meeting.
Meetings will be held virtually. The first meeting will be on Friday, March 15th.
Schedule: Biweekly on Friday, 16:30-17:30(GMT+08:00) CST / 9:30-10:30 CET

**Comment by bigludo7** [comment]
Hello
Interested also to follow & join this project :)

**Comment by ShutingQing** [comment]
> Hello Interested also to follow & join this project :)

Hi, Ludovic and Rafal. @bigludo7 @rartych  Thanks for your interest. :)  I feel sorry that we were in our Chinese Lunar New Year Festvial in Feb, that our first meeting was postponed. The Frist Meeting will be started from Mar.15th, Biweekly on Friday. 16:30-17:30(GMT+08:00) CST / 9:30-10:30 CET . Welcome to join. 

Link: https://teams.live.com/meet/9559310154416?p=X9GldgzTnpV6NUdx

**Comment by ShutingQing** [comment]
linked to [https://github.com/camaraproject/RegionUserCount/pull/2](url)

**Comment by ShutingQing** [comment]
@philipxujin Would you please help on closing the issue?
