### ISSUE TITLE
MOM-2024-3-15

### ISSUE THREAD

**Issue by ShutingQing** [camaraproject/RegionUserCount#4]
**Problem description**
MOM-2024-3-15

**Expected action**

**Additional context**

**Comment by gregory1g** [comment]
Two points:
1) 29th of March (date of the next meeting) is a public holiday in many countries (Easter) 
2) what about a dedicated meeting for this API work group?

**Comment by ShutingQing** [comment]
Yes, Gregory, we've cancelled the meeting on March 29th. And a dedicated meeting for this API has been arranged.
